<?xml version="1.0" encoding="utf-8"?><Database Name="JB2-Bowtie" Class="BowtieDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=cx8yl1ofvr.database.windows.net;Initial Catalog=JB2-Bowtie;User ID=polkadot;Connect Timeout=60" SettingsObjectName="JB2.Bowtie.Data.Linq.Properties.Settings" SettingsPropertyName="JB2_BowtieConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.jb2bt_Client_Get" Method="jb2bt_Client_Get">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="jb2bt_Client_GetResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Application_Get" Method="jb2bt_Application_Get">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="publickey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="jb2bt_Application_GetResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublicKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Secret" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Client_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Achievement_Save" Method="jb2bt_Achievement_Save">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="applicationKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="sortOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="achievementType" Type="System.Int32" DbType="Int" />
    <Parameter Name="category" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="steps" Type="System.Int32" DbType="Int" />
    <Parameter Name="iconEarned" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="iconHidden" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="iconShown" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="eventStart" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="eventEnd" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="points" Type="System.Int32" DbType="Int" />
    <Parameter Name="saveMode" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="jb2bt_Achievement_SaveResult">
      <Column Name="Success" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Player_Achievement_Get" Method="jb2bt_Player_Achievement_Get">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="playerKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="achievementKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="jb2bt_Player_Achievement_GetResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObjectKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Player_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Achievement_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CurrentStep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AchievementFlags" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Player_Achievement_Save" Method="jb2bt_Player_Achievement_Save">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="playerKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="achievementKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="currentStep" Type="System.Int32" DbType="Int" />
    <Parameter Name="achievementFlags" Type="System.Int32" DbType="Int" />
    <Parameter Name="pointsEarned" Type="System.Int32" DbType="Int" />
    <Parameter Name="saveMode" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="jb2bt_Player_Achievement_SaveResult">
      <Column Name="Success" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Achievement_Get" Method="jb2bt_Achievement_Get">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="applicationKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="jb2bt_Achievement_GetResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObjectKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Application_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AchievementType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="StepsRequire" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IconUrlEarned" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IconUrlHidden" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IconUrlShown" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="EventStartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EventEndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PointsWorth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RarityLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Game_Command_Get" Method="jb2bt_Game_Command_Get">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gameKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="jb2bt_Game_Command_GetResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObjectKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Application_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Game_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Issued_Player_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Affected_Player_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CommandCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Game_Command_Save" Method="jb2bt_Game_Command_Save">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="applicationKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gameKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="issuedPlayerKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="affectedPlayerKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="commandCode" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="saveMode" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="jb2bt_Game_Command_SaveResult">
      <Column Name="Success" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Leaderboard_Get" Method="jb2bt_Leaderboard_Get">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="masterKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="jb2bt_Leaderboard_GetResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObjectKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IconUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreFormat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreLowerLimit" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ScoreUpperLimit" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ScoreOrderType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateEventStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEventEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MasterLeaderboard_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Application_Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.jb2bt_Leaderboard_Save" Method="jb2bt_Leaderboard_Save">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="iconurl" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="type" Type="System.Int32" DbType="Int" />
    <Parameter Name="listOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="scoreFormat" Type="System.Int32" DbType="Int" />
    <Parameter Name="scoreLowerLimit" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="scoreUpperLimit" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="scoreOrderType" Type="System.Int32" DbType="Int" />
    <Parameter Name="dateEventStart" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="dateEventEnd" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="masterLeaderboardKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="applicationKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="saveMode" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="jb2bt_Leaderboard_SaveResult">
      <Column Name="Success" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>