#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB2.Bowtie.Data.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JB2-Bowtie")]
	public partial class BowtieDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BowtieDataContext() : 
				base(global::JB2.Bowtie.Data.Linq.Properties.Settings.Default.JB2_BowtieConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BowtieDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BowtieDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BowtieDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BowtieDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Client_Get")]
		public ISingleResult<jb2bt_Client_GetResult> jb2bt_Client_Get([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, key);
			return ((ISingleResult<jb2bt_Client_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Achievement_Save")]
		public ISingleResult<jb2bt_Achievement_SaveResult> jb2bt_Achievement_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string applicationKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> achievementType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> steps, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string iconEarned, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string iconHidden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string iconShown, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> eventStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> eventEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> points, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string saveMode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, name, applicationKey, sortOrder, description, achievementType, category, steps, iconEarned, iconHidden, iconShown, eventStart, eventEnd, points, saveMode);
			return ((ISingleResult<jb2bt_Achievement_SaveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Player_Achievement_Get")]
		public ISingleResult<jb2bt_Player_Achievement_GetResult> jb2bt_Player_Achievement_Get([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string playerKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string achievementKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, playerKey, achievementKey);
			return ((ISingleResult<jb2bt_Player_Achievement_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Player_Achievement_Save")]
		public ISingleResult<jb2bt_Player_Achievement_SaveResult> jb2bt_Player_Achievement_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string playerKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string achievementKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> currentStep, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> achievementFlags, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pointsEarned, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string saveMode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, name, playerKey, achievementKey, currentStep, achievementFlags, pointsEarned, saveMode);
			return ((ISingleResult<jb2bt_Player_Achievement_SaveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Achievement_Get")]
		public ISingleResult<jb2bt_Achievement_GetResult> jb2bt_Achievement_Get([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string applicationKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, applicationKey);
			return ((ISingleResult<jb2bt_Achievement_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Game_Command_Get")]
		public ISingleResult<jb2bt_Game_Command_GetResult> jb2bt_Game_Command_Get([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gameKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, gameKey);
			return ((ISingleResult<jb2bt_Game_Command_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Game_Command_Save")]
		public ISingleResult<jb2bt_Game_Command_SaveResult> jb2bt_Game_Command_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string applicationKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gameKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string issuedPlayerKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string affectedPlayerKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string commandCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string saveMode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, name, applicationKey, gameKey, issuedPlayerKey, affectedPlayerKey, commandCode, saveMode);
			return ((ISingleResult<jb2bt_Game_Command_SaveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Leaderboard_Get")]
		public ISingleResult<jb2bt_Leaderboard_GetResult> jb2bt_Leaderboard_Get([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string masterKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, masterKey);
			return ((ISingleResult<jb2bt_Leaderboard_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Leaderboard_Save")]
		public ISingleResult<jb2bt_Leaderboard_SaveResult> jb2bt_Leaderboard_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string iconurl, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> listOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> scoreFormat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> scoreLowerLimit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> scoreUpperLimit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> scoreOrderType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateEventStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateEventEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string masterLeaderboardKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string applicationKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string saveMode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, name, iconurl, type, listOrder, scoreFormat, scoreLowerLimit, scoreUpperLimit, scoreOrderType, dateEventStart, dateEventEnd, masterLeaderboardKey, applicationKey, saveMode);
			return ((ISingleResult<jb2bt_Leaderboard_SaveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jb2bt_Application_Get")]
		public ISingleResult<jb2bt_Application_GetResult> jb2bt_Application_Get([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string publickey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, publickey);
			return ((ISingleResult<jb2bt_Application_GetResult>)(result.ReturnValue));
		}
	}
	
	public partial class jb2bt_Client_GetResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Key;
		
		public jb2bt_Client_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(10)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="VarChar(50)")]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this._Key = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Achievement_SaveResult
	{
		
		private System.Nullable<bool> _Success;
		
		private string _Key;
		
		private string _Message;
		
		public jb2bt_Achievement_SaveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Success", DbType="Bit")]
		public System.Nullable<bool> Success
		{
			get
			{
				return this._Success;
			}
			set
			{
				if ((this._Success != value))
				{
					this._Success = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="VarChar(50)")]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this._Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(100)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Player_Achievement_GetResult
	{
		
		private int _Id;
		
		private string _ObjectKey;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private string _Player_Key;
		
		private string _Achievement_Key;
		
		private System.Nullable<int> _CurrentStep;
		
		private System.Nullable<int> _AchievementFlags;
		
		public jb2bt_Player_Achievement_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectKey", DbType="VarChar(50)")]
		public string ObjectKey
		{
			get
			{
				return this._ObjectKey;
			}
			set
			{
				if ((this._ObjectKey != value))
				{
					this._ObjectKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Player_Key", DbType="VarChar(50)")]
		public string Player_Key
		{
			get
			{
				return this._Player_Key;
			}
			set
			{
				if ((this._Player_Key != value))
				{
					this._Player_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achievement_Key", DbType="VarChar(50)")]
		public string Achievement_Key
		{
			get
			{
				return this._Achievement_Key;
			}
			set
			{
				if ((this._Achievement_Key != value))
				{
					this._Achievement_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStep", DbType="Int")]
		public System.Nullable<int> CurrentStep
		{
			get
			{
				return this._CurrentStep;
			}
			set
			{
				if ((this._CurrentStep != value))
				{
					this._CurrentStep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AchievementFlags", DbType="Int")]
		public System.Nullable<int> AchievementFlags
		{
			get
			{
				return this._AchievementFlags;
			}
			set
			{
				if ((this._AchievementFlags != value))
				{
					this._AchievementFlags = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Player_Achievement_SaveResult
	{
		
		private System.Nullable<bool> _Success;
		
		private string _Key;
		
		private string _Message;
		
		public jb2bt_Player_Achievement_SaveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Success", DbType="Bit")]
		public System.Nullable<bool> Success
		{
			get
			{
				return this._Success;
			}
			set
			{
				if ((this._Success != value))
				{
					this._Success = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="VarChar(50)")]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this._Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(100)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Achievement_GetResult
	{
		
		private int _Id;
		
		private string _ObjectKey;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private string _Application_Key;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Description;
		
		private System.Nullable<int> _AchievementType;
		
		private string _Category;
		
		private System.Nullable<int> _StepsRequire;
		
		private string _IconUrlEarned;
		
		private string _IconUrlHidden;
		
		private string _IconUrlShown;
		
		private System.Nullable<System.DateTime> _EventStartTime;
		
		private System.Nullable<System.DateTime> _EventEndTime;
		
		private System.Nullable<int> _PointsWorth;
		
		private int _RarityLevel;
		
		public jb2bt_Achievement_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectKey", DbType="VarChar(50)")]
		public string ObjectKey
		{
			get
			{
				return this._ObjectKey;
			}
			set
			{
				if ((this._ObjectKey != value))
				{
					this._ObjectKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_Key", DbType="VarChar(50)")]
		public string Application_Key
		{
			get
			{
				return this._Application_Key;
			}
			set
			{
				if ((this._Application_Key != value))
				{
					this._Application_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this._SortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AchievementType", DbType="Int")]
		public System.Nullable<int> AchievementType
		{
			get
			{
				return this._AchievementType;
			}
			set
			{
				if ((this._AchievementType != value))
				{
					this._AchievementType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(25)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StepsRequire", DbType="Int")]
		public System.Nullable<int> StepsRequire
		{
			get
			{
				return this._StepsRequire;
			}
			set
			{
				if ((this._StepsRequire != value))
				{
					this._StepsRequire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconUrlEarned", DbType="VarChar(200)")]
		public string IconUrlEarned
		{
			get
			{
				return this._IconUrlEarned;
			}
			set
			{
				if ((this._IconUrlEarned != value))
				{
					this._IconUrlEarned = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconUrlHidden", DbType="VarChar(200)")]
		public string IconUrlHidden
		{
			get
			{
				return this._IconUrlHidden;
			}
			set
			{
				if ((this._IconUrlHidden != value))
				{
					this._IconUrlHidden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconUrlShown", DbType="VarChar(200)")]
		public string IconUrlShown
		{
			get
			{
				return this._IconUrlShown;
			}
			set
			{
				if ((this._IconUrlShown != value))
				{
					this._IconUrlShown = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventStartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EventStartTime
		{
			get
			{
				return this._EventStartTime;
			}
			set
			{
				if ((this._EventStartTime != value))
				{
					this._EventStartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventEndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EventEndTime
		{
			get
			{
				return this._EventEndTime;
			}
			set
			{
				if ((this._EventEndTime != value))
				{
					this._EventEndTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsWorth", DbType="Int")]
		public System.Nullable<int> PointsWorth
		{
			get
			{
				return this._PointsWorth;
			}
			set
			{
				if ((this._PointsWorth != value))
				{
					this._PointsWorth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RarityLevel", DbType="Int NOT NULL")]
		public int RarityLevel
		{
			get
			{
				return this._RarityLevel;
			}
			set
			{
				if ((this._RarityLevel != value))
				{
					this._RarityLevel = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Game_Command_GetResult
	{
		
		private int _Id;
		
		private string _ObjectKey;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private string _Application_Key;
		
		private string _Game_Key;
		
		private string _Issued_Player_Key;
		
		private string _Affected_Player_Key;
		
		private string _CommandCode;
		
		public jb2bt_Game_Command_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectKey", DbType="VarChar(50)")]
		public string ObjectKey
		{
			get
			{
				return this._ObjectKey;
			}
			set
			{
				if ((this._ObjectKey != value))
				{
					this._ObjectKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_Key", DbType="VarChar(50)")]
		public string Application_Key
		{
			get
			{
				return this._Application_Key;
			}
			set
			{
				if ((this._Application_Key != value))
				{
					this._Application_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Game_Key", DbType="VarChar(50)")]
		public string Game_Key
		{
			get
			{
				return this._Game_Key;
			}
			set
			{
				if ((this._Game_Key != value))
				{
					this._Game_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issued_Player_Key", DbType="VarChar(50)")]
		public string Issued_Player_Key
		{
			get
			{
				return this._Issued_Player_Key;
			}
			set
			{
				if ((this._Issued_Player_Key != value))
				{
					this._Issued_Player_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Affected_Player_Key", DbType="VarChar(50)")]
		public string Affected_Player_Key
		{
			get
			{
				return this._Affected_Player_Key;
			}
			set
			{
				if ((this._Affected_Player_Key != value))
				{
					this._Affected_Player_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommandCode", DbType="VarChar(255)")]
		public string CommandCode
		{
			get
			{
				return this._CommandCode;
			}
			set
			{
				if ((this._CommandCode != value))
				{
					this._CommandCode = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Game_Command_SaveResult
	{
		
		private System.Nullable<bool> _Success;
		
		private string _Key;
		
		private string _Message;
		
		public jb2bt_Game_Command_SaveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Success", DbType="Bit")]
		public System.Nullable<bool> Success
		{
			get
			{
				return this._Success;
			}
			set
			{
				if ((this._Success != value))
				{
					this._Success = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="VarChar(50)")]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this._Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(100)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Leaderboard_GetResult
	{
		
		private int _Id;
		
		private string _ObjectKey;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private string _IconUrl;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<int> _ListOrder;
		
		private System.Nullable<int> _ScoreFormat;
		
		private System.Nullable<long> _ScoreLowerLimit;
		
		private System.Nullable<long> _ScoreUpperLimit;
		
		private System.Nullable<int> _ScoreOrderType;
		
		private System.Nullable<System.DateTime> _DateEventStart;
		
		private System.Nullable<System.DateTime> _DateEventEnd;
		
		private string _MasterLeaderboard_Key;
		
		private string _Application_Key;
		
		public jb2bt_Leaderboard_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectKey", DbType="VarChar(50)")]
		public string ObjectKey
		{
			get
			{
				return this._ObjectKey;
			}
			set
			{
				if ((this._ObjectKey != value))
				{
					this._ObjectKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconUrl", DbType="VarChar(200)")]
		public string IconUrl
		{
			get
			{
				return this._IconUrl;
			}
			set
			{
				if ((this._IconUrl != value))
				{
					this._IconUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListOrder", DbType="Int")]
		public System.Nullable<int> ListOrder
		{
			get
			{
				return this._ListOrder;
			}
			set
			{
				if ((this._ListOrder != value))
				{
					this._ListOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreFormat", DbType="Int")]
		public System.Nullable<int> ScoreFormat
		{
			get
			{
				return this._ScoreFormat;
			}
			set
			{
				if ((this._ScoreFormat != value))
				{
					this._ScoreFormat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreLowerLimit", DbType="BigInt")]
		public System.Nullable<long> ScoreLowerLimit
		{
			get
			{
				return this._ScoreLowerLimit;
			}
			set
			{
				if ((this._ScoreLowerLimit != value))
				{
					this._ScoreLowerLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreUpperLimit", DbType="BigInt")]
		public System.Nullable<long> ScoreUpperLimit
		{
			get
			{
				return this._ScoreUpperLimit;
			}
			set
			{
				if ((this._ScoreUpperLimit != value))
				{
					this._ScoreUpperLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreOrderType", DbType="Int")]
		public System.Nullable<int> ScoreOrderType
		{
			get
			{
				return this._ScoreOrderType;
			}
			set
			{
				if ((this._ScoreOrderType != value))
				{
					this._ScoreOrderType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEventStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEventStart
		{
			get
			{
				return this._DateEventStart;
			}
			set
			{
				if ((this._DateEventStart != value))
				{
					this._DateEventStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEventEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEventEnd
		{
			get
			{
				return this._DateEventEnd;
			}
			set
			{
				if ((this._DateEventEnd != value))
				{
					this._DateEventEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterLeaderboard_Key", DbType="VarChar(50)")]
		public string MasterLeaderboard_Key
		{
			get
			{
				return this._MasterLeaderboard_Key;
			}
			set
			{
				if ((this._MasterLeaderboard_Key != value))
				{
					this._MasterLeaderboard_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_Key", DbType="VarChar(50)")]
		public string Application_Key
		{
			get
			{
				return this._Application_Key;
			}
			set
			{
				if ((this._Application_Key != value))
				{
					this._Application_Key = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Leaderboard_SaveResult
	{
		
		private System.Nullable<bool> _Success;
		
		private string _Key;
		
		private string _Message;
		
		public jb2bt_Leaderboard_SaveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Success", DbType="Bit")]
		public System.Nullable<bool> Success
		{
			get
			{
				return this._Success;
			}
			set
			{
				if ((this._Success != value))
				{
					this._Success = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="VarChar(50)")]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this._Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(100)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
	}
	
	public partial class jb2bt_Application_GetResult
	{
		
		private int _ID;
		
		private string _PublicKey;
		
		private string _Name;
		
		private string _Secret;
		
		private string _Client_Key;
		
		private System.Nullable<bool> _CanIssueJBeans;
		
		public jb2bt_Application_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicKey", DbType="VarChar(50)")]
		public string PublicKey
		{
			get
			{
				return this._PublicKey;
			}
			set
			{
				if ((this._PublicKey != value))
				{
					this._PublicKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secret", DbType="VarChar(50)")]
		public string Secret
		{
			get
			{
				return this._Secret;
			}
			set
			{
				if ((this._Secret != value))
				{
					this._Secret = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_Key", DbType="VarChar(50)")]
		public string Client_Key
		{
			get
			{
				return this._Client_Key;
			}
			set
			{
				if ((this._Client_Key != value))
				{
					this._Client_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanIssueJBeans", DbType="Bit")]
		public System.Nullable<bool> CanIssueJBeans
		{
			get
			{
				return this._CanIssueJBeans;
			}
			set
			{
				if ((this._CanIssueJBeans != value))
				{
					this._CanIssueJBeans = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
